version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build:

services:
  backend:
    build: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

    env_file:
      - .env.docker
    depends_on:
      - db
  frontend:
    build: frontend
    volumes:
      - react_build:/react/build

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.docker

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend