# Generated by Django 4.2.5 on 2023-10-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BankCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atms', to='map.bank')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atms', to='map.bankcoordinates')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='map.bank')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='map.bankcoordinates')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='coordinates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='map.bankcoordinates'),
        ),
    ]
