# Generated by Django 4.2.5 on 2023-10-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='coordinates',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='bankbranch',
            old_name='coordinates',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='individualatm',
            old_name='coordinates',
            new_name='street',
        ),
    ]
