# Generated by Django 4.2.5 on 2023-10-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('capability', models.CharField(choices=[('SUPPORTED', 'SUPPORTED'), ('UNKNOWN', 'UNKNOWN'), ('UNSUPPORTED', 'UNSUPPORTED')], max_length=60, verbose_name='Возможность оказания услуг')),
                ('activity', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE'), ('UNKNOWN', 'UNKNOWN')], max_length=60, verbose_name='Доступность услуги в текущий момент времени')),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('allDay', models.BooleanField(verbose_name='Работает круглосуточно')),
                ('services', models.ManyToManyField(to='bank.atmservice')),
            ],
        ),
    ]
