# Generated by Django 4.2.5 on 2023-10-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_point_name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='Статус')),
                ('rko', models.CharField(max_length=20, null=True, verbose_name='Наличие РКО')),
                ('office_type', models.CharField(max_length=50, null=True, verbose_name='Тип отделения')),
                ('sale_point_format', models.CharField(max_length=50, null=True, verbose_name='Формат отделения')),
                ('suo_availability', models.CharField(max_length=5, null=True, verbose_name='Доступность СУО')),
                ('has_ramp', models.CharField(max_length=5, null=True, verbose_name='Наличие рампы')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('metro_station', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ближайшая станция метро')),
                ('distance', models.PositiveIntegerField(null=True, verbose_name='Расстояние')),
                ('kep', models.BooleanField(default=False, null=True, verbose_name='КЭП')),
                ('my_branch', models.BooleanField(default=False, null=True, verbose_name='Мой отдел')),
                ('review_count', models.CharField(max_length=50, null=True, verbose_name='Количество отзывов')),
                ('estimation', models.CharField(max_length=10, null=True, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Отделение банка',
                'verbose_name_plural': 'Отделения банков',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=2, null=True)),
                ('hours', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='atm',
            options={'verbose_name': 'АТМ(банкомат)', 'verbose_name_plural': 'АТМ(банкоматы)'},
        ),
        migrations.AlterModelOptions(
            name='atmservice',
            options={'verbose_name': 'Сервис АТМ', 'verbose_name_plural': 'Сервисы АТМ'},
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, null=True)),
                ('hour', models.CharField(max_length=50, null=True)),
                ('people_count', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('stars', models.PositiveIntegerField(null=True, verbose_name='Оценка')),
                ('text', models.TextField(null=True, verbose_name='Текст комментария')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='bank.bankbranch', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='open_hours',
            field=models.ManyToManyField(related_name='branch_opening_hours', to='bank.openinghours', verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='open_hours_individual',
            field=models.ManyToManyField(related_name='individual_opening_hours', to='bank.openinghours', verbose_name='Индивидуальные часы работы'),
        ),
    ]
